### PR TITLE
move scRNAseq from suggests to depends

### LINKED ISSUE #15: Unspecified dependency on package "scRNAseq" in example("writeH5AD")
this is a fairly trivial fix, will open a PR

### PR DESCRIPTION
**Pull request by ttriche**
fixes #15 so that example("writeH5AD") runs out of the box

### CODE REVIEW

**Comment by LTLA** [comment]
**scRNAseq** as a `Suggests` is wholly intentional, developers who are importing **zellkonverter** should not be expected to drag in **scRNAseq** (and **ExperimentHub** and its ~70 dependencies).

Having **scRNAseq** as a `Suggests` for use in examples is convention for, like, every package:

https://bioconductor.org/packages/devel/data/experiment/html/scRNAseq.html

**Comment by lazappi** [comment]
I agree that we shouldn't depend on **scRNAseq** to avoid the dependencies. We should check that it is installed as part of examples/tests. I will open an issue for this. Might also be good to include a small test dataset as part of the package. There is one at the moment but it's fairly limited.

**Comment by LTLA** [comment]
I don't think that any further action is required. The examples clearly state `library(scRNAseq)`. Doesn't get any clearer or more explicit than that. In fact, I don't even think that your:

https://github.com/theislab/zellkonverter/blob/bd65a42406216198dde25c244ec7af112d974cbc/R/read.R#L58-L61

is required, the automatic error message is pretty self-explanatory:

```
> blah::asdsad
Error in loadNamespace(name) : there is no package called ‘blah’
```

**Comment by ttriche** [comment]
It does, however, mean that the example for a function that crashes under several circumstances will fail out of the box. Easily remedied, to be sure, but it will fail unless packages in Suggests are also installed (which as you know is not the default). 

Perhaps, to avoid scRNAseq’s dependencies, a smallish SingleCellExperiment created using readH5AD() might make more sense. This would also provide a more straightforward way to test any curious bits that fall off when going from .h5ad to SCE to .h5ad or vice versa. (In an ideal world these would be isomorphic) As a result of investigating why valid SCEs crash or error out from writeH5AD(), whether imported using readH5AD() or constructed from scratch, I now have a couple such examples, although “smallish” they are currently not. 

I’ll see what I can do about this, unless the current state of affairs is the desired state, which might limit uptake somewhat. (For example, running cellrank on an SCE will likely be hampered if it can’t be exported.) Given size or dimension constraints, I’m quite certain I can provide one. 

--t

**Comment by LTLA** [comment]
I don't understand what the problem is. If **scRNAseq** is not installed, then it's pretty clear that it needs to be installed. I don't see a justification for including more serialized content, which is difficult to accept from both a theoretical perspective (minimize binary files on Git) and a practical one (obsolescence on SCE class updates).

The export problem seems to be unrelated to the current issue of the use of **scRNAseq** in the examples. The latter is fully intentional and the use of real datasets is more demonstrative than some toy SCE provided with the package.

**Comment by lazappi** [comment]
One reason I see to include a small test dataset is to make sure that there is something in each of the slots that are being converted (in both directions). I haven't checked properly but I don't know if that is true for the datasets in **scRNAseq**. This is probably more for tests though, real data probably makes sense for examples/vignette.

**Comment by LTLA** [comment]
For tests, it is much more expedient to just construct an SCE with the desired properties, e.g., in a `setup.R` file.

**Comment by ttriche** [comment]
The attraction for a .h5ad file as example/test data is that it allows for easily confirming whether writeH5AD(readH5AD(“foo.h5ad”), “foo_zelltest.h5ad”) is isomorphic.

Conversely, if a small randomly constructed SCE is saved and reloaded via readH5AD(writeH5AD(SCE, “sce_zelltest.h5ad”)), that tests round tripping in the other direction. 

I’ll chop down one of the h5ad files the has given zellkonverter trouble and see if I can’t automate both. 

--t

**Comment by LTLA** [comment]
Let's just stop for a second. We ALREADY have an embedded H5AD file, there is no need to construct another one. And we KNOW that the object does not survive a round trip, see some of the issues and the `?AnnData2SCE` documentation.

It has still not been made clear to me EXACTLY what the problem is here and how it is related to **scRNAseq**.

**Comment by ttriche** [comment]
Closing; not relevant to underlying issue.

**Comment by ttriche** [comment]
fair points all, now reading the documentation for readH5AD and seeing this

Most of this arose as a result of my poking around trying to figure out
what does and does not break writeH5AD().

I think this can be closed, whether or not a test SCE comes from scRNAseq
is not the issue here; more likely, I need to fiddle with the internals
more to see what eats RAM and doesn't, and how to better handle the
corresponding trade-offs.

Closing.



--t

**Pull request closed without merging**
